version: "3"
services:
  besu:
    image: "tmio/besu:fix_disc"
    container_name: "besu"
    ports:
      - 8545:8545
      - 30303:30303
      - 30303:30303/udp
      - 8008:8008
    volumes:
     - ./genesis.json:/var/genesis.json
     - ./data:/var/data
    command: --genesis-file=/var/genesis.json --fast-sync-min-peers=1 --data-path=/var/data --rpc-http-api=admin,eth,debug,miner,net,txpool,priv,trace,web3 --rpc-http-cors-origins="all" --host-allowlist=* 
    restart: unless-stopped
  faucet:
    image: "tmio/tuweni:1.5.0-dev"
    container_name: "faucet"
    ports:
      - 8080:8080
    volumes:
     - ./wallet:/var/wallet
     - ./application.yml:/usr/tuweni/bin/application.yml
    entrypoint: /usr/tuweni/bin/eth-faucet
